# Generated by Django 5.1.2 on 2024-10-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Soups', 'SOUPS'), ('Stews', 'STEWS'), ('Proteins', 'PROTEINS'), ('Side Dishes', 'SIDE_DISHES'), ('Rice', 'RICE')], max_length=100, null=True),
        ),
    ]
